name: 04 - Using Actions
on: push
jobs:
  build-to-the-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: echo "checkout the repository code into the current working directory."
      - name: Install Dependencies
